language: scala
scala:
- 2.13.1
jobs:
  include:
    - stage: compilation
      script: 
      - sbt -jvm-opts travis/jvmopts.compile ... compile
    - stage: test
      script: 
      - sbt ++$TRAVIS_SCALA_VERSION test